services:
  - type: web
    name: tcria
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
